version: '3.9'
services:
  mariadb:
    container_name: hsa9_mysql
    image: mariadb:11.2.2
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/etc/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: hsa9
      MYSQL_USER: hsa9
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"

volumes:
  mysql_data:
    driver: local
